name 'pmon_cassandra'
maintainer 'Yuriy Novikov'
maintainer_email 'jv.novikov@agileprofi.ru'
license 'all_rights'
description 'Installs/Configures ruby'
long_description 'Installs/Configures ruby'
version '0.1.0'

#depends 'rvm', '~> 0.9.4'
depends 'java', '~> 1.50.0'
depends 'firewalld', '~> 1.1.5'