development:
  hosts: 
    - '192.168.5.3'
  port: 9042
  keyspace: dev
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

test:
  host: '192.168.5.3'
  port: 9042
  keyspace: app_test
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

production:
  hosts:
    #- '212.24.39.34'
    - '212.24.39.35'
    - '212.24.39.36'
    - '212.24.39.37'
    #- '212.24.39.38'
  port: 9042
  keyspace: mmp
#  username: 'myappuser'
#  password: 'password1'
  max_retries: 3
  retry_delay: 0.5
  newrelic: false
  replication:
    class: SimpleStrategy
    replication_factor: 1
# replication:
#   class: NetworkTopologyStrategy
#   datacenter1: 3
#   datacenter2: 2
# durable_writes: false
